# Generated by Django 4.0.8 on 2023-01-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Battery',
            new_name='ProductBattery',
        ),
        migrations.RenameModel(
            old_name='Body',
            new_name='ProductBody',
        ),
        migrations.RenameModel(
            old_name='Component',
            new_name='ProductComponent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
